name:                gloomhaven-ai-solver
version:             0.1.0.0
github:              "MHova/gloomhaven-ai-solver"
license:             BSD3
author:              "Michael Ho"
maintainer:          "michael.chinghei.ho@gmail.com"
copyright:           "2020 Michael Ho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MHova/gloomhaven-ai-solver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gloomhaven-ai-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloomhaven-ai-solver

tests:
  gloomhaven-ai-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloomhaven-ai-solver
